fastlane_version "1.98.0"

lane :test_ios12 do
  scan(devices: ["iPhone X (12.2)"])
  sh "bash ../codecov.sh"
end

lane :test_ios11 do
  scan(devices: ["iPhone X (11.4)"])
end

lane :test_tvos12 do
  scan(device: "Apple TV")
end

lane :test_tvos11 do
  scan(device: "Apple TV")
end

lane :test_ios_swift4 do
  scan(devices: ["iPhone X (12.2)"], xcargs: "SWIFT_VERSION=4.2")
end

lane :test_tvos_swift4 do
  scan(devices: ["Apple TV"], xcargs: "SWIFT_VERSION=4.2")
end

lane :test_macos do
  scan(destination: "arch=x86_64")
  sh "bash ../codecov.sh"
end

lane :build_watchos do
  xcodebuild(
    build: true,
    destination: "OS=5.2,name=Apple Watch Series 4 - 44mm",
    scheme: 'Transporter'
  )
end

lane :pod_lint do
  sh "bundle exec pod repo update"
  pod_lib_lint(allow_warnings: true, verbose: true)
end

lane :carthage_build do
  carthage(command: "build", no_skip_current: true, verbose: false)
end

lane :spm_macos do
  sh "swift build"
end

lane :release do |params|
  version = params[:version]

  abort "You must specify a version in semver format." if version.nil? || version.scan(/\d+\.\d+\.\d+(-\w+\.\d+)?/).length == 0

  puts "Setting Framework version"
  increment_version_number(version_number: version)

  Dir.chdir("..") do

    puts "Updating podspec."
    filename = "Transporter.podspec"
    contents = File.read(filename)
    contents.gsub!(/s\.version\s*=\s"\d+\.\d+\.\d+(-\w+\.\d)?"/, "s.version      = \"#{version}\"")
    File.open(filename, 'w') { |file| file.puts contents }

    puts "Updating changelog."
    changelog_filename = "CHANGELOG.md"
    changelog = File.read(changelog_filename)
    changelog.gsub!(/# Next/, "# Next\n\n## [#{version}](https://github.com/DenHeadless/Transporter/releases/tag/#{version})")
    File.open(changelog_filename, 'w') { |file| file.puts changelog }

    puts "Comitting, tagging, and pushing."
    message = "Releasing version #{version}."
    sh "git commit -am '#{message}'"
    sh "git tag #{version} -m '#{message}'"
    sh "git push --follow-tags"

    puts "Pushing to CocoaPods trunk."
    sh "bundle exec pod trunk push Transporter.podspec --allow-warnings"

    puts "Preparing Carthage binary framework."
    sh "carthage build --no-skip-current"
    sh "carthage archive Transporter"

    puts "Pushing as a GitHub Release."
    fastlane_require 'octokit'
    stripped_changelog = changelog.split(/^## /)[1].split("\n")[1..-1].join("\n").strip
    Octokit::Client.new(netrc: true).
      create_release('DenTelezhkin/Transporter',
                     version,
                     name: version,
                     body: stripped_changelog)

     puts "Attaching Carthage prebuilt binary to release."
     releases = client.releases('DenTelezhkin/Transporter')
     client.upload_asset(releases[0].url, 'Transporter.framework.zip')
     sh "rm -rf ../Transporter.framework.zip"
  end
end
